# Generated by Django 5.1.7 on 2025-03-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('user_type', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('donor', 'Donor')], max_length=12)),
                ('sub_type', models.CharField(choices=[('ngo', 'NGO'), ('college', 'College'), ('company', 'Company'), ('personal', 'Personal')], max_length=12)),
                ('ngo_college_company_id', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
